# Generated by Django 2.2.4 on 2019-09-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qusetions', models.CharField(max_length=200, unique=True)),
                ('choice1', models.ImageField(unique=True, upload_to='')),
                ('choice2', models.ImageField(unique=True, upload_to='')),
                ('choice3', models.ImageField(unique=True, upload_to='')),
                ('choice4', models.ImageField(unique=True, upload_to='')),
                ('correct_answer', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
