# Generated by Django 2.2.4 on 2019-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinequiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='qusetions',
            new_name='questions',
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice1',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice2',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice3',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice4',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
