# Generated by Django 2.2.4 on 2019-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinequiz', '0004_auto_20190913_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
